services:
  flask-app:
    build: .
    command: flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    volumes:
      - .:/backend
      - ./uploads:/backend/uploads
      - ./processed:/backend/processed
    environment:
      - FLASK_APP=backend.app
      - FLASK_ENV=development
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - app-network

  frontend:
    image: node:14-alpine
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    command: ["npx", "http-server", "-p", "8000"]
    ports:
      - "8000:8000"
    networks:
      - app-network

  grobid:
    image: lfoppiano/grobid:0.8.0
    ports:
      - "8070:8070"
    networks:
      - app-network

  celery-worker:
    build: .
    
    command: celery -A backend.app.celery worker --loglevel=info --concurrency=1
    volumes:
      - .:/backend
      - ./uploads:/backend/uploads
      - ./processed:/backend/processed
    depends_on:
      - redis
    networks:
      - app-network
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery-beat:
    build: .

    command: celery -A backend.app.celery beat --loglevel=info
    volumes:
      - .:/backend
    depends_on:
      - redis
    networks:
      - app-network
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  